FROM python:3.8
COPY . /app
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    libsm6 \
    libxext6 \
    ffmpeg \
    libgl1-mesa-glx \
    portaudio19-dev \
    gcc 
RUN apt-get install -y libasound2-dev libpulse-dev
RUN apt-get install -y portaudio19-dev && pip install pyaudio
RUN pip install -r requirements.txt
EXPOSE 80
RUN mkdir ~/.streamlit
RUN cp config.toml ~/.streamlit/config.toml
RUN cp secrets.toml ~/.streamlit/secrets.toml.toml
ENTRYPOINT [ "streamlit", "run" ]
CMD [ "app.py" ]