# Use the official Python base image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

COPY requirements.txt ./requirements.txt

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libsm6 \
    libxext6 \
    ffmpeg \
    libgl1-mesa-glx \
    portaudio19-dev

# Install Python dependencies
RUN pip install -r requirements.txt

# Expose the specified port
EXPOSE 8501

# Copy the project files to the working directory
COPY . /app

ENTRYPOINT ["streamlit", "run"]

# Run the Streamlit app
CMD ["app.py"]
